[package]
name = "pigin"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.16"
crossterm = "0.28.1"
nom = "7.1.3"
ratatui = "0.28.0"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "warn"
